### ISSUE TITLE
[Stocks] Wrong stock price bug

### ISSUE THREAD

**Issue by Habchy** [Flame442/FlameCogs#46]
**Describe the bug**
*The last two digits of the stock price are supposed to be decimals but the cog adds them to the actual number causing the price of stocks to be much higher than real life.*

**To Reproduce**
*Run the [p]stock price <stock name> command*

**Error code**
*N/A*

**Comment by Flame442** [comment]
That is not a bug, that is documented behavior. Red economy credits are stored in integers, so they cannot have decimals. Because of that and the price of most stocks is quite low compared to the average balance of users, I opted to have a conversion rate of $1 = 100 credits. This is visible in `[p]help stock buy`.
