### ISSUE TITLE
Monopoly gives duplicate text when choosing an AI or Player

### ISSUE THREAD

**Issue by deXxterlab97** [Flame442/FlameCogs#52]
**Describe the bug**
![Screenshot_20200905-191952_Discord](https://user-images.githubusercontent.com/31835797/92309303-16da3000-efad-11ea-9305-0e0deaa8f553.jpg)

**To Reproduce**
*Commands or inputs given before the bug occurred*

**Error code**
*Result of `[p]traceback` (if applicable)*

**Additional information**
*Any other relevant information*

**Comment by Flame442** [comment]
This can be reproduced by running `[p]monopoly` twice before doing any other input to the prompt, however since the cog will not allow you to create two games at once anyway, I'm going to say this isn't an issue that needs to be fixed.
![image](https://user-images.githubusercontent.com/34169552/92311737-d74d1d00-ef87-11ea-8cbe-c74899a37af5.png)
