### ISSUE TITLE
Image implementation for the state of duel 

### ISSUE THREAD

**Issue by cryosphericleaf** [Flame442/FlameCogs#78]
Thoughts on using image for state of duel in the pokemonduel cog instead of a standard text message?
I have made a certain implementation for it and can submit a PR for your review if you approve.

**Comment by Flame442** [comment]
When PokemonDuel was originally written for Mewbot, it had an image preview instead of a text preview using the images of pokemon that the bot was already using. I didn't really want to deal with sourcing, potentially hosting, or the copyright of using images of the pokemon for the Red cog, so I just stuck to a text representation. I'm not really interested in adding image support now for those same reasons, but if I were to add it back at some point I would probably just use the code I already have.
